language: php
php:
  - 5.6
  - 7.0

# install dependencies
install:
  - travis_retry composer install --no-interaction

# Submit code coverage report
after_success:
 - bash <(curl -s https://codecov.io/bash)